# Generated by Django 4.2.6 on 2023-10-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RutaDeAutobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParadaDeAutobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDeParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_de_la_semana', models.CharField(max_length=20)),
                ('hora_de_llegada', models.TimeField()),
                ('hora_de_salida', models.TimeField()),
                ('parada_de_autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.paradadeautobus')),
                ('ruta_de_autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.rutadeautobus')),
            ],
        ),
    ]
