# Generated by Django 4.2.6 on 2023-10-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionParadaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.paradadeautobus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.rutadeautobus')),
            ],
        ),
    ]
