# Generated by Django 4.2.6 on 2023-10-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_asociacionparadaruta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsociacionParadaRuta',
            new_name='AsociacionParadaRutas',
        ),
    ]
