# Generated by Django 4.2.6 on 2023-10-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_rename_asociacionparadaruta_asociacionparadarutas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsociacionParadaRutas',
            new_name='AsociacionParadaRuta',
        ),
    ]
